backend/models/Set.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "colin_set".
 *
 * @property string $id 系统设置表
 * @property string $key 键
 * @property string $desc 描述
 * @property string $value 值
 * @property int $type 类型 1:文本 2:图片
 */
class Set extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'colin_set';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type'], 'integer'],
            [['key'], 'string', 'max' => 50],
            [['key'], 'unique'],
            [['desc', 'value'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'key' => '键',
            'desc' => '描述',
            'value' => '值',
            'type' => '类型',
        ];
    }
}

backend/controllers/SetController.php
<?php
/**
 * User: Colin
 * Time: 2019/3/26 19:12
 */

namespace backend\controllers;


use backend\models\Set;
use common\models\UploadForm;
use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;

class SetController extends BaseController
{
    public function actionIndex()
    {
        $texts = Set::find()->where(['type' => 1])->all();
        $images = Set::find()->where(['type' => 2])->all();
        return $this->render('index', compact('texts', 'images'));
    }

    public function actionChangeText()
    {
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $set = Set::findOne($post['id']);
            if (!$set) {
                return $this->json(100, '参数错误');
            }
            $set->value = $post['val'];
            if (!$set->save()) {
                return $this->json(100, '修改失败');
            }
            return $this->json(200, '修改成功');
        }
    }

    public function actionChangeImg()
    {
        if (Yii::$app->request->isPost) {
            $model = new UploadForm();
            $model->imageFile = UploadedFile::getInstanceByName('file');
            $res = $model->upload();
            if ($res['status'] == 200) {
                return $this->json(200, '上传成功', $res['path']);
            } else {
                return $this->json(100, $res['msg']);
            }
        }
        if (Yii::$app->request->isGet) {
            $get = Yii::$app->request->get();
            $set = Set::findOne($get['id']);
            if (!$set) {
                return $this->json(100, '参数错误');
            }
            $set->value = $get['val'];
            if (!$set->save()) {
                return $this->json(100, '修改失败');
            }
            return $this->json(200, '修改成功');
        }
    }


}

backend/views/set/index.php
<?php
use yii\helpers\Url;
?>

<?php $this->beginBlock('header') ?>
<style>
    .layui-form-pane .layui-form-label {width: 200px}
    .layui-form-pane .layui-input-block {margin-left: 200px}
    .layui-input-inline img {width: 100px; height: 100px; border: 1px solid #ccc; box-sizing: border-box}
    .img-item .layui-form-label{height: 100px; line-height: 80px}
</style>
<?php $this->endBlock() ?>

<div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="javascript:;">首页</a>
        <a href="javascript:;">系统设置</a>
        <a href="javascript:;">
          <cite>系统设置列表</cite>
        </a>
      </span>
    <a class="layui-btn layui-btn-small refresh-btn" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:38px">ဂ</i></a>
</div>

<div class="x-body">
    <div class="layui-tab layui-tab-brief">
        <ul class="layui-tab-title">
            <li class="layui-this">网站设置</li>
            <li>图片设置</li>
        </ul>
        <div class="layui-tab-content" >
            <div class="layui-tab-item layui-show">
                <form class="layui-form layui-form-pane" action="">
                    <?php foreach ($texts as $list): ?>
                    <div class="layui-form-item">
                        <label class="layui-form-label">
                            <span class='x-red'>*</span> <?= $list['desc'] ?>
                        </label>
                        <div class="layui-input-block sys-text">
                            <input type="text" name="title" autocomplete="off" class="layui-input" data-id="<?= $list['id'] ?>"
                                   value="<?= $list['value'] ?>">
                        </div>
                    </div>
                    <?php endforeach; ?>
                </form>
                <div style="height:100px;"></div>
            </div>
            <div class="layui-tab-item">
                <form class="layui-form layui-form-pane" action="">
                    <?php foreach ($images as $list): ?>
                    <div class="layui-form-item img-item" >
                        <label class="layui-form-label">
                            <span class='x-red'>*</span> <?= $list['desc'] ?>
                        </label>
                        <div class="layui-input-inline sys-img">
                            <img src="<?= $list['value'] ? Url::to('@web' . $list['value']) : Url::to('@web/images/add_img.png') ?>"
                                 data-id="<?= $list['id'] ?>">
                        </div>
                    </div>
                    <?php endforeach; ?>
                </form>
            </div>
        </div>
    </div>
</div>

<form id="uploadForm" enctype="multipart/form-data" style="display: none">
    <input type="file" name="file" id="file">
</form>

<?php $this->beginBlock('footer') ?>
<script>
    $('.sys-text input').blur(function () {
        var id = $(this).attr('data-id');
        var val = $(this).val();
        layer.load(3);
        $.post('<?= Url::to(['set/change-text']) ?>', {id: id, val: val}, function (res) {
            layer.closeAll();
            if (res.status !== 200) {
                layer.msg(res.msg, {icon: 2, time: 1500})
            }
        }, 'json');
    })

    $('.sys-img img').click(function () {
        var id = $(this).attr('data-id');
        var fileObj = $('#file');
        var that = $(this);
        fileObj.unbind().click();
        fileObj.change(function(){
            layer.load(3);
            $.ajax({
                url: '<?= Url::to(['set/change-img']) ?>',
                type: 'POST',
                cache: false,
                data: new FormData($('#uploadForm')[0]),
                dataType:'JSON',
                processData: false,
                contentType: false
            }).done(function(res) {
                layer.closeAll();
                if (res.status === 100) {
                    layer.msg(res.msg, {icon: 2, time: 1500}); return;
                }
                that.attr('src', res.data);
                layer.load(3);
                $.get('<?= Url::to(['set/change-img']) ?>', {id: id, val: res.data}, function (res) {
                    layer.closeAll();
                    console.log(res)
                }, 'json')
            });
        });
    })

</script>
<?php $this->endBlock() ?>